import type { DiagramWindowCopy, DiagramWindowLocale } from "./diagramWindowTypes";

const DIAGRAM_WINDOW_COPY: Record<DiagramWindowLocale, DiagramWindowCopy> = {
  en: {
    emptyPreview: "Select a file to preview diagram content.",
    noDiagramDetected: "No diagram detected",
    noDiagramHint: "Current file is not a BPMN XML file and does not contain Mermaid blocks.",
    markdownAnalysisLoading: "Analyzing Markdown structure for diagram projection...",
    codeAnalysisLoading: "Analyzing code AST structure for diagram projection...",
    modeTabLabel: "Diagram mode",
    modeBpmnLabel: "BPMN",
    modeCombinedLabel: "Combined",
    modeMermaidLabel: "Mermaid",
    modeBpmnAria: "BPMN diagram",
    modeCombinedAria: "Combined view",
    modeMermaidAria: "Mermaid diagram",
    headingBoth: "BPMN + Mermaid Preview",
    headingBpmn: "BPMN Diagram",
    headingMermaid: "Rendered Mermaid Diagrams",
    panelBpmn: "BPMN-js",
    panelMermaid: "Mermaid",
    diagramIndexPrefix: "Diagram",
    mermaidRenderFailedPrefix: "Mermaid render failed",
    mermaidUnsupported: "Unsupported Mermaid dialect for inline render",
    noMermaidBody: "No Mermaid diagram body was found in this file.",
    emptyMermaidSource: "Empty Mermaid diagram source",
    resetViewLabel: "Reset view",
    bpmnLoading: "Loading BPMN runtime...",
    mermaidLoading: "Loading Mermaid runtime...",
  },
  zh: {
    emptyPreview: "请选择文件以预览图示内容。",
    noDiagramDetected: "未检测到图示",
    noDiagramHint: "当前文件既不是 BPMN XML，也不包含 Mermaid 代码块。",
    markdownAnalysisLoading: "正在解析 Markdown 结构并生成图示...",
    codeAnalysisLoading: "正在解析代码 AST 结构并生成图示...",
    modeTabLabel: "图示模式",
    modeBpmnLabel: "BPMN",
    modeCombinedLabel: "组合",
    modeMermaidLabel: "Mermaid",
    modeBpmnAria: "BPMN 图示",
    modeCombinedAria: "组合视图",
    modeMermaidAria: "Mermaid 图示",
    headingBoth: "BPMN + Mermaid 预览",
    headingBpmn: "BPMN 图示",
    headingMermaid: "Mermaid 渲染图示",
    panelBpmn: "BPMN-js",
    panelMermaid: "Mermaid",
    diagramIndexPrefix: "图示",
    mermaidRenderFailedPrefix: "Mermaid 渲染失败",
    mermaidUnsupported: "当前内联渲染不支持的 Mermaid 方言",
    noMermaidBody: "当前文件未找到 Mermaid 图示内容。",
    emptyMermaidSource: "Mermaid 图示源码为空",
    resetViewLabel: "重置视图",
    bpmnLoading: "正在加载 BPMN 运行时...",
    mermaidLoading: "正在加载 Mermaid 运行时...",
  },
};

export function getDiagramWindowCopy(locale: DiagramWindowLocale): DiagramWindowCopy {
  return DIAGRAM_WINDOW_COPY[locale];
}
