// Auto-generated from xiuxian-wendao
// Run: cargo run --bin export_types --features studio


// This file has been generated by Specta. Do not edit this file manually.
// A relationship edge in the document IR.
export type AnalysisEdge = {
	// Edge identifier.
	id: string,
	// Source node identifier.
	sourceId: string,
	// Target node identifier.
	targetId: string,
	// Relationship kind.
	kind: AnalysisEdgeKind,
	// Display label.
	label: string,
	// Evidence metadata.
	evidence: AnalysisEvidence,
};

// Kind of an analysis edge.
export type AnalysisEdgeKind = 
// Parent-child hierarchy.
"parent" | 
// Semantic reference or mention.
"mentions" | 
// Document membership.
"contains" | 
// Next task in sequence.
"nextstep" | 
// Explicit document reference.
"references";

// Metadata about an analysis edge evidence.
export type AnalysisEvidence = {
	// Evidence file path.
	path: string,
	// 1-based start line.
	lineStart: number,
	// 1-based end line.
	lineEnd: number,
	// Confidence score (0.0 - 1.0).
	confidence: number,
};

// A single node in the structural IR of a document.
export type AnalysisNode = {
	// Node identifier.
	id: string,
	// Node kind.
	kind: AnalysisNodeKind,
	// Display label.
	label: string,
	// Nesting depth.
	depth: number,
	// 1-based start line.
	lineStart: number,
	// 1-based end line.
	lineEnd: number,
	// Optional parent node identifier.
	parentId?: string | null,
};

// Kind of an analysis node.
export type AnalysisNodeKind = 
// Markdown section heading.
"section" | 
// Task list item.
"task" | 
// Observation/evidence block.
"observation" | 
// Symbolic link or relation.
"relation" | 
// Document-level node.
"document" | 
// Code block node.
"codeblock" | 
// Markdown table node.
"table" | 
// Display math node.
"math" | 
// Semantic reference site.
"reference" | 
// Property box node.
"property" | 
// Symbolic entity node.
"symbol";

// Base error for Studio API.
export type ApiError = {
	// Machine-readable error code.
	code: string,
	// Human-readable message.
	message: string,
	// Optional failure details.
	details?: string | null,
};

// A single hit in an AST definition search.
export type AstSearchHit = {
	// Captured definition name.
	name: string,
	// Signature line or skeleton snippet.
	signature: string,
	// Source file path relative to the project root.
	path: string,
	// Source language name.
	language: string,
	// Owning crate or package name.
	crateName: string,
	// Configured project name when the source path maps to a studio project.
	projectName?: string | null,
	// Configured root label when the source path maps to a project root path.
	rootLabel?: string | null,
	// Optional AST node kind for richer Markdown search presentation.
	nodeKind?: string | null,
	// Optional owning Markdown section title/path for property-box derived hits.
	ownerTitle?: string | null,
	// Display-ready navigation target for opening this hit in studio.
	navigationTarget: StudioNavigationTarget,
	// 1-based start line.
	lineStart: number,
	// 1-based end line.
	lineEnd: number,
	// Search relevance score.
	score: number,
};

// Response for studio AST definition search queries.
export type AstSearchResponse = {
	// Original query string.
	query: string,
	// Matching AST hits.
	hits: AstSearchHit[],
	// Total number of hits returned.
	hitCount: number,
	// Selected AST scope.
	selectedScope: string,
	// Whether the response is partial because the AST index is still warming.
	partial?: boolean,
	// Current AST-index lifecycle state.
	indexingState?: string | null,
	// Optional AST-index error surfaced without blocking the request path.
	indexError?: string | null,
};

// A hit representing an attachment or external resource.
export type AttachmentSearchHit = {
	// Attachment filename.
	name: string,
	// Relative path.
	path: string,
	// Stable source document identifier.
	sourceId: string,
	// Source document stem.
	sourceStem: string,
	// Source document title.
	sourceTitle: string,
	// Source document path.
	sourcePath: string,
	// Stable attachment identifier.
	attachmentId: string,
	// Relative attachment path.
	attachmentPath: string,
	// Attachment display name.
	attachmentName: string,
	// Lowercased attachment extension without leading dot.
	attachmentExt: string,
	// Attachment kind label.
	kind: string,
	// Navigation target.
	navigationTarget: StudioNavigationTarget,
	// Relevance score.
	score: number,
	// Optional OCR or vision snippet for the attachment.
	visionSnippet?: string | null,
};

// Response for Studio attachment search queries.
export type AttachmentSearchResponse = {
	// Original query string.
	query: string,
	// Matching attachment hits.
	hits: AttachmentSearchHit[],
	// Total number of hits returned.
	hitCount: number,
	// Selected attachment scope label.
	selectedScope: string,
	// Whether the response is partial because the attachment index is still warming.
	partial?: boolean,
	// Current attachment-index lifecycle state.
	indexingState?: string | null,
	// Optional attachment-index error surfaced without blocking the request path.
	indexError?: string | null,
};

// Response for Studio autocomplete queries.
export type AutocompleteResponse = {
	// Original prefix used to generate suggestions.
	prefix: string,
	// Ranked autocomplete suggestions.
	suggestions: AutocompleteSuggestion[],
};

// A single autocomplete suggestion.
export type AutocompleteSuggestion = {
	// Suggestion text emitted to the caller.
	text: string,
	// Logical suggestion classification.
	suggestionType: string,
};

// Response payload for code AST analysis.
export type CodeAstAnalysisResponse = {
	// Repository identifier.
	repoId: string,
	// Repository-relative source path.
	path: string,
	// Source language.
	language: string,
	// Total number of AST nodes.
	nodeCount: number,
	// Total number of AST edges.
	edgeCount: number,
	// AST nodes.
	nodes: CodeAstNode[],
	// AST edges.
	edges: CodeAstEdge[],
	// Projection summaries.
	projections: CodeAstProjection[],
	// Compact retrieval atoms for declaration- and symbol-backed surfaces.
	retrievalAtoms?: RetrievalChunk[],
	// Optional node identifier selected by line hint.
	focusNodeId?: string | null,
	// Diagnostics emitted by parser/analyzer.
	diagnostics: string[],
};

// A single AST edge entry for diagram rendering.
export type CodeAstEdge = {
	// Edge identifier.
	id: string,
	// Source node identifier.
	sourceId: string,
	// Target node identifier.
	targetId: string,
	// Semantic edge kind.
	kind: CodeAstEdgeKind,
	// Optional display label.
	label?: string | null,
};

// Kind of a code-AST edge.
export type CodeAstEdgeKind = 
// Ownership / nesting relation.
"contains" | 
// Call relation.
"calls" | 
// Usage relation.
"uses" | 
// Import relation.
"imports" | 
// Other relation.
"other";

// A single AST node entry for diagram rendering.
export type CodeAstNode = {
	// Node identifier.
	id: string,
	// Display label.
	label: string,
	// Semantic node kind.
	kind: CodeAstNodeKind,
	// Optional source path.
	path?: string | null,
	// Optional 1-based source start line.
	lineStart?: number | null,
	// Optional 1-based source end line.
	lineEnd?: number | null,
};

// Kind of a code-AST node.
export type CodeAstNodeKind = 
// Module/namespace container.
"module" | 
// Function/method declaration.
"function" | 
// Type/struct/class declaration.
"type" | 
// Constant declaration.
"constant" | 
// External symbol imported from outside the file.
"external_symbol" | 
// Other AST entities.
"other";

// Precomputed AST projection metadata.
export type CodeAstProjection = {
	// Projection category.
	kind: CodeAstProjectionKind,
	// Number of nodes included in projection.
	nodeCount: number,
	// Number of edges included in projection.
	edgeCount: number,
};

// Kind of an AST projection view.
export type CodeAstProjectionKind = 
// Containment projection.
"contains" | 
// Call-graph projection.
"calls" | 
// Usage projection.
"uses";

// Response for native studio definition resolution.
export type DefinitionResolveResponse = {
	// Original query string.
	query: string,
	// Optional source path used to bias resolution.
	sourcePath?: string | null,
	// Optional source line used by the caller.
	sourceLine?: number | null,
	// Number of candidate definitions considered for this resolution.
	candidateCount: number,
	// The selected scope used to resolve the definition.
	selectedScope: string,
	// Display-ready navigation target for the resolved definition.
	navigationTarget: StudioNavigationTarget,
	// The resolved definition hit.
	definition: DefinitionSearchHit,
	// Display-ready navigation target for the resolved definition.
	resolvedTarget?: StudioNavigationTarget | null,
	// The actual hit that was resolved.
	resolvedHit?: DefinitionSearchHit | null,
};

// Result of a best-definition resolution.
export type DefinitionSearchHit = {
	// Symbol or definition name.
	name: string,
	// Display signature for the definition.
	signature: string,
	// Repository-relative path to the definition.
	path: string,
	// Source language label for the definition.
	language: string,
	// Owning crate or repository identifier.
	crateName: string,
	// Optional project grouping label.
	projectName?: string | null,
	// Optional root label derived from configured project scopes.
	rootLabel?: string | null,
	// Optional AST node kind for the resolved symbol.
	nodeKind?: string | null,
	// Optional owner title or containing symbol label.
	ownerTitle?: string | null,
	// Navigation target for opening the definition in Studio.
	navigationTarget: StudioNavigationTarget,
	// 1-based starting line for the definition span.
	lineStart: number,
	// 1-based ending line for the definition span.
	lineEnd: number,
	// Resolution score assigned to this candidate.
	score: number,
	// Hints derived from :OBSERVE: property boxes.
	observationHints: ObservationHint[],
};

// A single edge in the link-graph visualization.
export type GraphLink = {
	// Source node identifier.
	source: string,
	// Target node identifier.
	target: string,
	// Relationship direction label.
	direction: string,
	// Hop distance for this edge.
	distance: number,
};

// Result of a graph neighbor traversal.
export type GraphNeighborsResponse = {
	// Center node.
	center: GraphNode,
	// Nodes in the neighbor subgraph.
	nodes: GraphNode[],
	// Links connecting the neighbors.
	links: GraphLink[],
	// Number of returned nodes.
	totalNodes: number,
	// Number of returned links.
	totalLinks: number,
};

// A single node in the link-graph visualization.
export type GraphNode = {
	// Global identifier for the node.
	id: string,
	// Display label.
	label: string,
	// File path if the node represents a document.
	path: string,
	// Display-ready navigation target.
	navigationTarget?: StudioNavigationTarget | null,
	// Optional node type (e.g., "CORE", "FEATURE").
	nodeType: string,
	// Whether this is the focal node of the query.
	isCenter: boolean,
	// Shortest-path distance from the center node.
	distance: number,
};

// One DeepWiki-style document link row.
export type MarkdownAnalysisDocumentLink = {
	// Display label shown in the reader.
	label: string,
	// Coarse source kind for the row.
	kind: MarkdownAnalysisDocumentLinkKind,
	// Original literal token when it exists in source markdown.
	literal?: string | null,
	// Explicit semantic relation type for metadata-owned links.
	relationType?: string | null,
	// Owning metadata scope for explicit relation rows.
	metadataOwner?: string | null,
	// Canonical target/source document id when resolution succeeds.
	docId?: string | null,
	// Studio-display path fallback for reader navigation.
	path?: string | null,
	// Best-effort resolved title for the linked document.
	title?: string | null,
	// Optional scoped target suffix such as `#Heading` or `#^block`.
	targetAddress?: string | null,
};

// DeepWiki-style document link kind emitted by markdown analysis.
export type MarkdownAnalysisDocumentLinkKind = 
// Ordinary structural body wikilink.
"body" | 
// Explicit semantic relation from metadata.
"relation" | 
// Docs-kernel `:RELATIONS: :LINKS:` edge.
"index" | 
// Resolved parent document edge.
"parent" | 
// Materialized backlink row from the reverse index.
"backlink";

// DeepWiki-style document identity payload emitted by markdown analysis.
export type MarkdownAnalysisDocumentMetadata = {
	// Canonical document id when the graph index can resolve the file.
	docId?: string | null,
	// Parser-owned document title.
	title: string,
	// Parser-owned document tags.
	tags?: string[],
	// Optional parser-owned semantic document type.
	docType?: string | null,
	// Best-effort updated timestamp from raw metadata.
	updated?: string | null,
	// Explicit docs-kernel parent link, when declared.
	parent?: MarkdownAnalysisDocumentLink | null,
	// Unified outgoing relation/index rows.
	outgoingLinks?: MarkdownAnalysisDocumentLink[],
	// Materialized reverse-index rows.
	backlinks?: MarkdownAnalysisDocumentLink[],
};

// Full response for Markdown analysis.
export type MarkdownAnalysisResponse = {
	// Analyzed file path.
	path: string,
	// Content fingerprint.
	documentHash: string,
	// Total number of nodes.
	nodeCount: number,
	// Total number of edges.
	edgeCount: number,
	// IR nodes.
	nodes: AnalysisNode[],
	// IR edges.
	edges: AnalysisEdge[],
	// Mermaid diagram projections.
	projections: MermaidProjection[],
	// Compact retrieval atoms for document / section surfaces.
	retrievalAtoms?: RetrievalChunk[],
	// Backend-owned DeepWiki document identity and link metadata.
	documentMetadata?: MarkdownAnalysisDocumentMetadata | null,
	// Analysis diagnostics.
	diagnostics: string[],
};

// A single Mermaid diagram projection.
export type MermaidProjection = {
	// Type of projection.
	kind: MermaidViewKind,
	// Generated Mermaid source.
	source: string,
	// Number of nodes in projection.
	nodeCount: number,
	// Number of edges in projection.
	edgeCount: number,
};

// Mermaid projection view kind.
export type MermaidViewKind = 
// Hierarchical document outline.
"outline" | 
// Task dependency graph.
"tasks" | 
// Semantic entity relations.
"knowledge";

// A hint for observing code patterns near a definition.
export type ObservationHint = {
	// Language constraint (e.g., "rust").
	language: string,
	// File path scope (e.g., "src/**").
	scope: string,
	// Pattern to observe.
	pattern: string,
};

// A hit indicating where a symbol is referenced or used.
export type ReferenceSearchHit = {
	// Symbol name being referenced.
	name: string,
	// Referencing file path.
	path: string,
	// Language of the referencing file.
	language: string,
	// Crate name of the referencing file.
	crateName: string,
	// Project grouping label.
	projectName?: string | null,
	// Root label.
	rootLabel?: string | null,
	// Navigation target for the reference site.
	navigationTarget: StudioNavigationTarget,
	// 1-based line number.
	line: number,
	// 1-based column number.
	column: number,
	// Snippet showing matching line.
	lineText: string,
	// Scoring weight.
	score: number,
};

// Response for Studio reference search queries.
export type ReferenceSearchResponse = {
	// Original query string.
	query: string,
	// Matching reference hits.
	hits: ReferenceSearchHit[],
	// Total number of hits returned.
	hitCount: number,
	// Selected reference scope label.
	selectedScope: string,
	// Whether the response is partial because the reference index is still warming.
	partial?: boolean,
	// Current reference-index lifecycle state.
	indexingState?: string | null,
	// Optional reference-index error surfaced without blocking the request path.
	indexError?: string | null,
};

// Shared retrieval chunk contract across markdown and code analysis surfaces.
export type RetrievalChunk = {
	// Owning node identifier.
	ownerId: string,
	// Stable retrieval chunk identifier.
	chunkId: string,
	// Semantic type for downstream retrieval / UI display.
	semanticType: string,
	// Stable semantic fingerprint.
	fingerprint: string,
	// Approximate token estimate.
	tokenEstimate: number,
	// Optional display label for UI-facing retrieval rails.
	displayLabel?: string | null,
	// Optional excerpt for UI-facing retrieval rails.
	excerpt?: string | null,
	// Optional 1-based start line.
	lineStart?: number | null,
	// Optional 1-based end line.
	lineEnd?: number | null,
	// Optional surface kind for richer UI routing.
	surface?: RetrievalChunkSurface | null,
	// Optional parser- or compiler-owned attributes for richer UI projection.
	attributes?: ([string, string])[],
};

// Surface kind for a shared retrieval chunk.
export type RetrievalChunkSurface = 
// Markdown document identity card.
"document" | 
// Markdown section card.
"section" | 
// Markdown code / mermaid rich slot.
"codeblock" | 
// Markdown table rich slot.
"table" | 
// Markdown display-math rich slot.
"math" | 
// Markdown observation / blockquote rich slot.
"observation" | 
// Code declaration surface.
"declaration" | 
// Code logic-block surface.
"block" | 
// Code symbol / anchor surface.
"symbol";

// Structured backlink metadata surfaced on search hits.
export type SearchBacklinkItem = {
	// Stable backlink identifier.
	id: string,
	// Optional display title.
	title?: string | null,
	// Optional source path.
	path?: string | null,
	// Optional relation kind.
	kind?: string | null,
};

// Unified search hit consumed by the frontend search surface.
export type SearchHit = {
	// Stable stem or primary identifier.
	stem: string,
	// Optional display title.
	title?: string | null,
	// Repository-relative or workspace-relative path.
	path: string,
	// Optional logical hit kind.
	docType?: string | null,
	// Search-visible tags.
	tags: string[],
	// Normalized score.
	score: number,
	// Optional best section or signature summary.
	bestSection?: string | null,
	// Optional match-reason string.
	matchReason?: string | null,
	// Optional hierarchical URI.
	hierarchicalUri?: string | null,
	// Optional hierarchy segments.
	hierarchy?: string[] | null,
	// Optional saliency score.
	saliencyScore?: number | null,
	// Optional audit status.
	auditStatus?: string | null,
	// Optional verification state.
	verificationState?: string | null,
	// Optional backlink identifiers.
	implicitBacklinks?: string[] | null,
	// Optional structured backlink items.
	implicitBacklinkItems?: SearchBacklinkItem[] | null,
	// Optional navigation target.
	navigationTarget?: StudioNavigationTarget | null,
};

// Unified search response consumed by the frontend search shell.
export type SearchResponse = {
	// Original query string.
	query: string,
	// Matching hits.
	hits: SearchHit[],
	// Total number of hits returned.
	hitCount: number,
	// Optional graph confidence score.
	graphConfidenceScore?: number | null,
	// Optional selected mode label.
	selectedMode?: string | null,
	// Optional resolved intent label.
	intent?: string | null,
	// Optional resolved intent confidence.
	intentConfidence?: number | null,
	// Optional backend search mode.
	searchMode?: string | null,
	/**
	 *  Whether the backend returned partial results because repo indexes are still warming or
	 *  because a repo-wide search exhausted its bounded server-side budget.
	 */
	partial?: boolean,
	// Optional aggregate indexing state for code search.
	indexingState?: string | null,
	// Repo ids that are still queued or indexing.
	pendingRepos?: string[],
	// Repo ids skipped because their repo index is unsupported or failed.
	skippedRepos?: string[],
};

// Navigation target for opening files/symbols in the Studio editor.
export type StudioNavigationTarget = {
	// Full path or URI.
	path: string,
	// Navigation category (e.g., "doc", "symbol").
	category: string,
	// Optional project label.
	projectName?: string | null,
	// Optional root label.
	rootLabel?: string | null,
	// 1-based line number.
	line?: number | null,
	// 1-based end line number.
	lineEnd?: number | null,
	// 1-based column number.
	column?: number | null,
};

// A hit in a project-wide symbol index (e.g. Tantivy-backed).
export type SymbolSearchHit = {
	// Symbol name.
	name: string,
	// Symbol kind (e.g. "fn", "struct").
	kind: string,
	// Display path.
	path: string,
	// 1-based line number for the symbol location.
	line: number,
	// Canonical `path:line` location string.
	location: string,
	// Source language label inferred from the symbol path.
	language: string,
	// Source identifier (e.g. "project", "external").
	source: string,
	// Owning crate name.
	crateName: string,
	// Project grouping label.
	projectName?: string | null,
	// Root label.
	rootLabel?: string | null,
	// Navigation target.
	navigationTarget: StudioNavigationTarget,
	// Semantic score.
	score: number,
};

// Response for Studio symbol search queries.
export type SymbolSearchResponse = {
	// Original query string.
	query: string,
	// Matching symbol hits.
	hits: SymbolSearchHit[],
	// Total number of hits returned.
	hitCount: number,
	// Selected symbol scope label.
	selectedScope: string,
	// Whether the response is partial because the symbol index is still warming.
	partial: boolean,
	// Current symbol-index lifecycle state.
	indexingState?: string | null,
	// Optional symbol-index error surfaced without blocking the request path.
	indexError?: string | null,
};

// Payload for 3D graph topology visualization.
export type Topology3dPayload = {
	// All nodes in the global graph.
	nodes: TopologyNode[],
	// All edges in the global graph.
	links: TopologyLink[],
	// Cluster summaries for grouped graph rendering.
	clusters: TopologyCluster[],
};

// Cluster metadata for the 3D topology graph.
export type TopologyCluster = {
	// Cluster identifier.
	id: string,
	// Human-friendly cluster label.
	name: string,
	// Cluster centroid.
	centroid: [number, number, number],
	// Number of nodes in the cluster.
	nodeCount: number,
	// Stable cluster display color.
	color: string,
};

// A single edge in the 3D topology graph.
export type TopologyLink = {
	// Source node identifier.
	from: string,
	// Target node identifier.
	to: string,
	// Optional edge label.
	label?: string | null,
};

// A single node in the 3D topology graph.
export type TopologyNode = {
	// Global identifier for the node.
	id: string,
	// Human-friendly node label.
	name: string,
	// Node category.
	nodeType: string,
	// Initial 3D position.
	position: [number, number, number],
	// Optional cluster identifier.
	clusterId?: string | null,
};

// Global UI configuration for Studio.
export type UiConfig = {
	// Local project roots to scan.
	projects: UiProjectConfig[],
	// External repository projects.
	repoProjects: UiRepoProjectConfig[],
};

// Configuration for a local project root.
export type UiProjectConfig = {
	// Unique name.
	name: string,
	// Relative path to project root.
	root: string,
	// Explicit subdirectories to index.
	dirs: string[],
};

// Configuration for an external analyzed repository.
export type UiRepoProjectConfig = {
	// Unique identifier.
	id: string,
	// Optional local path.
	root?: string | null,
	// Optional upstream URL.
	url?: string | null,
	// Optional git reference.
	gitRef?: string | null,
	// Refresh policy.
	refresh?: string | null,
	// Enabled analysis plugins.
	plugins: string[],
};

// Category classification for VFS entries.
export type VfsCategory = 
// Directory/folder.
"folder" | 
// Skill definition file.
"skill" | 
// Documentation file.
"doc" | 
// Knowledge base file.
"knowledge" | 
// Other/uncategorized file.
"other";

// Payload for file content operations.
export type VfsContentResponse = {
	// Full path to the file.
	path: string,
	// MIME content type.
	contentType: string,
	// Raw file content.
	content: string,
	// File modification timestamp.
	modified: number,
};

// A single entry in the VFS (file or directory).
export type VfsEntry = {
	// Full path relative to the VFS root.
	path: string,
	// File or directory name.
	name: string,
	// Whether this entry is a directory.
	isDir: boolean,
	// File size in bytes (0 for directories).
	size: number,
	// Last modified timestamp (Unix seconds).
	modified: number,
	// MIME content type guess for files.
	contentType?: string | null,
	// Project grouping label for multi-root monorepo views.
	projectName?: string | null,
	// Root label under the grouped project node.
	rootLabel?: string | null,
	// Configured project root used to resolve this VFS root.
	projectRoot?: string | null,
	// Configured project directories associated with the resolved root.
	projectDirs?: string[] | null,
};

// A scanned entry with metadata for VFS tree display.
export type VfsScanEntry = {
	// Full path relative to the VFS root.
	path: string,
	// File or directory name.
	name: string,
	// Whether this entry is a directory.
	isDir: boolean,
	// Category classification for UI styling.
	category: VfsCategory,
	// File size in bytes (0 for directories).
	size: number,
	// Last modified timestamp (Unix seconds).
	modified: number,
	// MIME content type guess for files.
	contentType?: string | null,
	// Whether the file has YAML frontmatter.
	hasFrontmatter: boolean,
	// Wendao document ID if indexed.
	wendaoId?: string | null,
	// Project grouping label for multi-root monorepo views.
	projectName?: string | null,
	// Root label under the grouped project node.
	rootLabel?: string | null,
	// Configured project root used to resolve this VFS root.
	projectRoot?: string | null,
	// Configured project directories associated with the resolved root.
	projectDirs?: string[] | null,
};

// Result of a VFS scan operation.
export type VfsScanResult = {
	// All entries found during the scan.
	entries: VfsScanEntry[],
	// Total number of files scanned.
	fileCount: number,
	// Total number of directories scanned.
	dirCount: number,
	// Time taken for the scan in milliseconds.
	scanDurationMs: number,
};
