import React, { useRef } from 'react';
import { assembleSearchBarControllerResult } from './searchBarControllerAssembler';
import { SEARCH_BAR_COPY } from './searchPresentation';
import { getDocIcon, highlightMatch } from './searchRenderUtils';
import { useSearchBarResetOnOpen } from './useSearchBarResetOnOpen';
import { useSearchBarRepoSlice } from './useSearchBarRepoSlice';
import { useSearchBarControllerState } from './useSearchBarControllerState';
import { useSearchBarControllerPresentation } from './useSearchBarControllerPresentation';
import type { SearchBarControllerResult, UseSearchBarControllerParams } from './searchBarControllerTypes';

export function useSearchBarController({
  isOpen,
  locale,
  onClose,
  onResultSelect,
  onReferencesResultSelect,
  onGraphResultSelect,
  onRuntimeStatusChange,
}: UseSearchBarControllerParams): SearchBarControllerResult {
  const {
    query,
    setQuery,
    results,
    setResults,
    isLoading,
    setIsLoading,
    searchMeta,
    setSearchMeta,
    selectedIndex,
    setSelectedIndex,
    error,
    setError,
    suggestions,
    setSuggestions,
    showSuggestions,
    setShowSuggestions,
    scope,
    setScope,
    sortMode,
    setSortMode,
    isComposing,
    setIsComposing,
    debouncedQuery,
    debouncedAutocomplete,
  } = useSearchBarControllerState();

  const copy = SEARCH_BAR_COPY[locale];
  const inputRef = useRef<HTMLInputElement>(null);

  const {
    parsedCodeInput,
    parsedCodeSearch,
    activeRepoFilter,
    primaryRepoFilter,
    repoFacet,
    repoOverviewStatus,
    repoSyncStatus,
    activeCodeFilterEntries,
    codeQuickExampleTokens,
    codeQuickScenarios,
  } = useSearchBarRepoSlice({
    query,
    debouncedQuery,
    debouncedAutocomplete,
    isOpen,
    scope,
    locale,
    results,
    showSuggestions,
    setSuggestions,
  });

  useSearchBarResetOnOpen({
    isOpen,
    inputRef,
    setQuery,
    setResults,
    setError,
    setSearchMeta,
    setSelectedIndex,
    setSuggestions,
    setShowSuggestions,
    setScope,
    setSortMode,
  });
  const {
    visibleSections,
    interactionProps,
    getSuggestionIcon,
    clearCodeFilters,
    removeCodeFilter,
    appendCodeFilterToken,
    insertCodeFilterPrefix,
    applyCodeScenario,
    handleSuggestionClick,
    searchShellProps,
    searchResultsPanelProps,
  } = useSearchBarControllerPresentation({
    isOpen,
    locale,
    copy,
    inputRef,
    controllerState: {
      query,
      setQuery,
      results,
      setResults,
      isLoading,
      setIsLoading,
      searchMeta,
      setSearchMeta,
      selectedIndex,
      setSelectedIndex,
      error,
      setError,
      suggestions,
      setSuggestions,
      showSuggestions,
      setShowSuggestions,
      scope,
      setScope,
      sortMode,
      setSortMode,
      isComposing,
      setIsComposing,
      debouncedQuery,
      debouncedAutocomplete,
    },
    repoSlice: {
      parsedCodeInput,
      parsedCodeSearch,
      activeRepoFilter,
      primaryRepoFilter,
      repoFacet,
      repoOverviewStatus,
      repoSyncStatus,
      activeCodeFilterEntries,
      codeQuickExampleTokens,
      codeQuickScenarios,
    },
    renderIcon: getDocIcon,
    renderTitle: highlightMatch,
    onClose,
    onResultSelect,
    onReferencesResultSelect,
    onGraphResultSelect,
    onRuntimeStatusChange,
  });

  return assembleSearchBarControllerResult({
    locale,
    copy,
    showSuggestions,
    suggestions,
    selectedIndex,
    renderSuggestionIcon: getSuggestionIcon,
    onSuggestionClick: handleSuggestionClick,
    onSuggestionHover: setSelectedIndex,
    activeCodeFilterEntries,
    codeQuickExampleTokens,
    codeQuickScenarios,
    onInsertPrefix: insertCodeFilterPrefix,
    onApplyExample: appendCodeFilterToken,
    onApplyScenario: applyCodeScenario,
    onRemoveFilter: removeCodeFilter,
    onClearFilters: clearCodeFilters,
    ...interactionProps,
    showCodeFilterHelper: scope === 'code',
    shellProps: searchShellProps,
    resultsPanelProps: searchResultsPanelProps,
  });
}
