import type { RepoDiagnosticsCopy, RepoDiagnosticsLocale } from './types';

export const REPO_DIAGNOSTICS_COPY: Record<RepoDiagnosticsLocale, RepoDiagnosticsCopy> = {
  en: {
    title: 'Repo index diagnostics',
    unsupported: 'Unsupported',
    failed: 'Failed',
    retry: 'Retry',
    retrying: 'Retrying...',
    filterAll: 'All',
    filterUnsupported: 'Unsupported',
    filterFailed: 'Failed',
    filterReasonAll: 'All reasons',
    filterFailureAll: 'All failure reasons',
    drawerTitle: 'Repo index diagnostics drawer',
    retryFilteredFailed: 'Retry filtered failed',
    retryingFilteredFailed: 'Retrying filtered failed...',
    unsupportedManifestTitle: 'Unsupported remediation manifest',
    copyUnsupportedManifest: 'Copy unsupported manifest',
    copiedUnsupportedManifest: 'Copied unsupported manifest',
    retryRepo: 'Retry repo',
    copyRepoDiagnostics: 'Copy repo diagnostics',
    copiedRepoDiagnostics: 'Copied repo diagnostics',
    downloadRemediationBundle: 'Download remediation bundle',
    downloadTriageBundle: 'Download current triage bundle',
    downloadCurrentDiagnosticsPack: 'Download current diagnostics pack',
    downloadFailurePlan: 'Download failure plan',
    downloadCurrentFailurePlan: 'Download current failure plan',
    downloadRemediationRunbook: 'Download remediation runbook',
    downloadCurrentRemediationRunbook: 'Download current remediation runbook',
    downloadRemediationCommand: 'Download remediation command',
    copyCurrentRemediationCommand: 'Copy current remediation command',
    copiedCurrentRemediationCommand: 'Copied current remediation command',
    downloadCurrentRemediationCommand: 'Download current remediation command',
    downloadConfigPatch: 'Download config patch',
    downloadCurrentConfigPatch: 'Download current config patch',
    copyFailurePreset: 'Copy failure preset',
    copiedFailurePreset: 'Copied failure preset',
    copyRemediationCommand: 'Copy remediation command',
    copiedRemediationCommand: 'Copied remediation command',
    copyFixTemplate: 'Copy fix template',
    copiedFixTemplate: 'Copied fix template',
    copyLinkGraphOnlyPreset: 'Copy link-graph-only preset',
    copiedLinkGraphOnlyPreset: 'Copied link-graph-only preset',
    fixHintMissingProject: 'Fix hint: add Project.toml at the repo root, or move docs-only projects to link-graph-only config with plugins=[].',
    fixHintGeneric: 'Fix hint: verify the repo layout and plugin assignment for this project before retrying.',
    fixHintTransientFailure: 'Suggested next step: retry this repo or failure family. If it repeats, lower the repo-index sync limit and inspect outbound GitHub connectivity.',
    fixHintAuthFailure: 'Suggested next step: verify git credentials or remote access before retrying. Requeues alone are unlikely to clear this failure.',
    fixHintGenericFailure: 'Suggested next step: inspect the raw failure message and repository configuration before retrying.',
  },
  zh: {
    title: '仓库索引诊断',
    unsupported: '不支持',
    failed: '失败',
    retry: '重试',
    retrying: '重试中...',
    filterAll: '全部',
    filterUnsupported: '不支持',
    filterFailed: '失败',
    filterReasonAll: '全部原因',
    filterFailureAll: '全部失败原因',
    drawerTitle: '仓库索引诊断抽屉',
    retryFilteredFailed: '重试当前失败筛选',
    retryingFilteredFailed: '当前失败筛选重试中...',
    unsupportedManifestTitle: '不支持项修复清单',
    copyUnsupportedManifest: '复制不支持项清单',
    copiedUnsupportedManifest: '已复制不支持项清单',
    retryRepo: '重试仓库',
    copyRepoDiagnostics: '复制仓库诊断',
    copiedRepoDiagnostics: '已复制仓库诊断',
    downloadRemediationBundle: '下载修复交接包',
    downloadTriageBundle: '下载当前诊断分片',
    downloadCurrentDiagnosticsPack: '下载当前诊断包',
    downloadFailurePlan: '下载失败计划',
    downloadCurrentFailurePlan: '下载当前失败计划',
    downloadRemediationRunbook: '下载修复运行手册',
    downloadCurrentRemediationRunbook: '下载当前修复运行手册',
    downloadRemediationCommand: '下载修复命令',
    copyCurrentRemediationCommand: '复制当前修复命令',
    copiedCurrentRemediationCommand: '已复制当前修复命令',
    downloadCurrentRemediationCommand: '下载当前修复命令',
    downloadConfigPatch: '下载配置补丁',
    downloadCurrentConfigPatch: '下载当前配置补丁',
    copyFailurePreset: '复制失败预设',
    copiedFailurePreset: '已复制失败预设',
    copyRemediationCommand: '复制修复命令',
    copiedRemediationCommand: '已复制修复命令',
    copyFixTemplate: '复制修复模板',
    copiedFixTemplate: '已复制修复模板',
    copyLinkGraphOnlyPreset: '复制 link-graph-only 预设',
    copiedLinkGraphOnlyPreset: '已复制 link-graph-only 预设',
    fixHintMissingProject: '修复提示：在仓库根目录补充 Project.toml，或者把仅文档项目改成 link-graph-only 的 plugins=[] 配置。',
    fixHintGeneric: '修复提示：先检查仓库布局和插件配置，再决定是否重试。',
    fixHintTransientFailure: '建议下一步：先重试当前仓库或当前失败族；如果重复出现，再降低 repo-index 同步上限并检查到 GitHub 的外连是否饱和。',
    fixHintAuthFailure: '建议下一步：先检查 git 凭据或远端访问权限，再决定是否重试。单纯重新入队通常无法消除此类失败。',
    fixHintGenericFailure: '建议下一步：先检查原始失败信息和仓库配置，再决定是否重试。',
  },
};
